6 things - Oct 1


1. ChatBot - customer support,  get info about courses and contact info 
2. Rag pdf example - generate insights,  ask more questions 
3. Video - processing : cctc footage metric, use sam2 for tracking person interest/ music shows / cricket 
4. Material ui integratiom - mobile friendly ui, app theme, dark or light 
5. Security- bearer token, add api key to frontemd to send requrst, implement authentication. 
6. Drone - simulation - version 1 : document and milelstome, offline data processing. 