site_name: onwards
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs
    - content.action
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - attr_list
  - md_in_html
docs_dir: .
site_dir: site
plugins:
  - same-dir
  - search
exclude_docs: |
  *.py
  node_modules/
  *.git
  venv